steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/cad-ai-479510/cloud-run-source-deploy/cad-ai/cad-ai:$SHORT_SHA', '.']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/cad-ai-479510/cloud-run-source-deploy/cad-ai/cad-ai:$SHORT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cad-ai'
      - '--image=us-east1-docker.pkg.dev/cad-ai-479510/cloud-run-source-deploy/cad-ai/cad-ai:$SHORT_SHA'
      - '--region=us-east1'
      - '--platform=managed'
      - '--service-account=585298725894-compute@developer.gserviceaccount.com'
      - '--set-env-vars=OPENAI_API_KEY=$$OPENAI_API_KEY,KITTYCAD_API_KEY=$$KITTYCAD_API_KEY,REDIS_URL=$$REDIS_URL'
      - '--port=3000'
      - '--concurrency=80'
      - '--timeout=300s'
      - '--cpu=1000m'
      - '--memory=512Mi'
      - '--startup-cpu-boost'
      - '--max-instances=20'
      - '--allow-unauthenticated'
    secretEnv: ['OPENAI_API_KEY', 'KITTYCAD_API_KEY', 'REDIS_URL']

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/585298725894/secrets/OPENAI_API_KEY/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/585298725894/secrets/KITTYCAD_API_KEY/versions/latest
      env: 'KITTYCAD_API_KEY'
    - versionName: projects/585298725894/secrets/REDIS_URL/versions/latest
      env: 'REDIS_URL'
